### ISSUE TITLE
Unexpected incorrect answer at Easy2's `showAll` 

### ISSUE THREAD

**Issue by sisisin** [uhyo/typescript-puzzle#5] opened 2020-03-22 03:33 UTC
Expected behavior: it should be correct when assign string to `arr`
Actual behavior: incorrect answer...

```
function showAll(arr: ?): void {
  for (const val of arr) {
    console.log(val);
  }
}
```

**Comment by uhyo** [comment] 2020-03-22 11:52
Thank you! The cause was that target was set to `es3` through compiler options.
Fixed by setting it to `esnext`.

**Closed** 2020-03-22 11:53 UTC
Labels: bug
